apiVersion: v1
data:
  condorHostConfig: |+
    {
{{- $count := .Values.condor_replica | int -}}
{{- $releaseName := .Release.Name -}}
{{- $domain := .Values.domain -}}
{{- range $i, $e := until $count }}
            "{{ $releaseName }}-condor-{{ $i }}.{{ $domain }}.default.svc.cluster.local": {
                    "pool": "{{ $releaseName }}-condor-{{ $i }}.{{ $domain }}.default.svc.cluster.local:19618",
                    "weight": 1
            }
{{- end }}
    }

  templateFile.sdf: |+
    executable = {executableFile}
    arguments = "-s {computingSite} -r {computingSite} -q {pandaQueueName} -j {prodSourceLabel} -i {pilotType} -w generic --pilot-user ATLAS --url https://pandaserver.cern.ch -d --harvester-submit-mode PULL --allow-same-user=False --job-type={jobType} --resource-type SCORE --pilotversion {pilotVersion} {pilotUrlOption}"
    initialdir = {accessPoint}
    universe = grid
    log = {logDir}/{logSubdir}/grid.$(Cluster).$(Process).log
    output = {logDir}/{logSubdir}/grid.$(Cluster).$(Process).out
    error = {logDir}/{logSubdir}/grid.$(Cluster).$(Process).err
    transfer_executable = True
    x509userproxy = {x509UserProxy}
    environment = "PANDA_JSID=harvester-{harvesterID} HARVESTER_ID={harvesterID} HARVESTER_WORKER_ID={workerID} APFMON=http://apfmon.lancs.ac.uk/api APFFID={harvesterID} APFCID=$(Cluster).$(Process)"
    +harvesterID = "{harvesterID}"
    +harvesterWorkerID = "{workerID}"

    grid_resource = nordugrid {ceHostname}
    nordugrid_rsl = (queue = {ceQueueName})(runtimeenvironment = APPS/HEP/ATLAS-SITE-LCG)(runtimeenvironment = ENV/PROXY)(jobname = arc_pilot)(count = 1)(countpernode = 1)(memory = 2000)(walltime = {requestWalltime})(cputime = {requestCputime})(environment = (PANDA_JSID harvester-{harvesterID})(HARVESTER_ID {harvesterID})(HARVESTER_WORKER_ID {workerID})(GTAG {gtag})(APFMON http://apfmon.lancs.ac.uk/api)(APFFID {harvesterID})(APFCID $(Cluster).$(Process)))

    +remote_jobuniverse = 5
    +remote_requirements = True
    +remote_ShouldTransferFiles = "YES"
    +remote_WhenToTransferOutput = "ON_EXIT"
    +remote_TransferOutput = ""
    
    +ioIntensity = {ioIntensity}
    periodic_remove = (JobStatus == 2 && (CurrentTime - EnteredCurrentStatus) > 604800)
    +remote_PeriodicRemove = (JobStatus == 5 && (CurrentTime - EnteredCurrentStatus) > 3600) || (JobStatus == 1 && globusstatus =!= 1 && (CurrentTime - EnteredCurrentStatus) > 86400)
    
    +sdfPath = "{sdfPath}"
    
    queue 1

kind: ConfigMap
metadata:
  creationTimestamp: null
  name: {{ .Release.Name }}-submitter-config
